# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28fb7180960b834272e33346ba894be797b755bf1375f2ca8b86fea1e3999bcad997ab74506cf80b3061123ca8a3bf511c967272e84024335ff895dd6db1c141

test:
  secret_key_base: 708f76187c608a15eeb93b7646b797a6be13ae9f2ccacc5ad140b1f24e5d8f1b6aeecb8295e944e1f6a5d3997b8744417c27aa252c968f62e244be552316287d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
